version: "0.1"
services:
  emails_db:
    container_name: emails_db
    environment:
      POSTGRES_DB: emails_db
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
    image: "postgres:latest"
    networks:
      - app_net
    ports:
      - "5432:5432"

  emails_management_api:
    restart: always
    build:
      context: .
    container_name: emails_management_api
    environment:
        SECRET_KEY: qwerty
        DB_USER: postgres
        DB_PASSWORD: postgres
        DB_HOST: emails_db
        DB_PORT: 5432
        DB_NAME: emails_db
    networks:
      - app_net
    ports:
     - "9876:3000"
    depends_on:
      - emails_db

networks:
    app_net:
        driver: bridge